// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "CoreMinimal.h"
#include "Kismet/BlueprintFunctionLibrary.h"
#include "MyBlueprintFunctionLibrary.generated.h"

/**
 * 
 */
UCLASS()
class SMC_BUILD_API UMyBlueprintFunctionLibrary : public UBlueprintFunctionLibrary
{
	GENERATED_BODY()

public:
	UFUNCTION(BlueprintCallable)
	static void MarkRenderStateDirty(UStaticMeshComponent* Comp);

	UFUNCTION(BlueprintCallable)
	static void MarkRenderDynamicDataDirty(UStaticMeshComponent* Comp);
};
